import { SiTransmission } from "react-icons/si"
import car_image1 from "./car (1).jpg"
import car_image2 from "./car (2).jpg"
import car_image3 from "./car (3).jpg"
import car_image4 from "./car (4).jpg"
import car_image5 from "./car (5).jpg"
import car_image6 from "./car (6).jpg"


export const cityList=['chandigarh','mohali','panchkula']
export const dummyCarData =[
    {
        id:"101",
owner:"Rahul Sharam",
brand:"Toyota",
model:"Innova Crysta",
image: car_image1,
year:"2022",
category:"Suv",
seating_capacity:"7",
fuel_type:"Disel",
transmission:"Manaul",
pricePerDay:"3500",
location:"chandigarh",
description:"Spacious 7-seater SUV, perfect for family trips and longs drives.Well maintained and comfortable.",
isAvailable:"true",
createdAt:"2026-03-17",
    },
        {
        id:"301",
owner:"Rahul Sharam",
brand:"Toyota",
model:"Innova Crysta",
image: car_image2,
year:"2022",
category:"Suv",
seating_capacity:"7",
fuel_type:"Disel",
transmission:"Manaul",
pricePerDay:"3500",
location:"chandigarh",
description:"Spacious 7-seater SUV, perfect for family trips and longs drives.Well maintained and comfortable.",
isAvailable:"true",
createdAt:"2026-03-17",
    },
    {
        id:"401",
owner:"Rahul Sharam",
brand:"Toyota",
model:"Innova Crysta",
image: car_image3,
year:"2022",
category:"Suv",
seating_capacity:"7",
fuel_type:"Disel",
transmission:"Manaul",
pricePerDay:"3500",
location:"chandigarh",
description:"Spacious 7-seater SUV, perfect for family trips and longs drives.Well maintained and comfortable.",
isAvailable:"true",
createdAt:"2026-03-17",
    },
    {
        id:"501",
owner:"Rahul Sharam",
brand:"Toyota",
model:"Innova Crysta",
image: car_image4,
year:"2022",
category:"Suv",
seating_capacity:"7",
fuel_type:"Disel",
transmission:"Manaul",
pricePerDay:"3500",
location:"chandigarh",
description:"Spacious 7-seater SUV, perfect for family trips and longs drives.Well maintained and comfortable.",
isAvailable:"true",
createdAt:"2026-03-17",
    },
    {
        id:"601",
owner:"Rahul Sharam",
brand:"Toyota",
model:"Innova Crysta",
image: car_image5,
year:"2022",
category:"Suv",
seating_capacity:"7",
fuel_type:"Disel",
transmission:"Manaul",
pricePerDay:"3500",
location:"chandigarh",
description:"Spacious 7-seater SUV, perfect for family trips and longs drives.Well maintained and comfortable.",
isAvailable:"true",
createdAt:"2026-03-17",
    },
    {
        id:"701",
owner:"Rahul Sharam",
brand:"Toyota",
model:"Innova Crysta",
image: car_image6,
year:"2022",
category:"Suv",
seating_capacity:"7",
fuel_type:"Disel",
transmission:"Manaul",
pricePerDay:"3500",
location:"chandigarh",
description:"Spacious 7-seater SUV, perfect for family trips and longs drives.Well maintained and comfortable.",
isAvailable:"true",
createdAt:"2026-03-17",
    },

]